import { GithubLogo, MagicWand } from "phosphor-react";
import { Button } from "./components/ui/button";
import { Separator } from "./components/ui/separator";
import { Textarea } from "./components/ui/textarea";
import { Label } from "./components/ui/label";
import { Slider } from "./components/ui/slider";
import { VideoInputForm } from "./components/video-input-form";
import { PromptSelect } from "./components/prompt-select";
import { useState } from "react";
import { useCompletion } from '@ai-sdk/react'
import { ModelSelect } from "./components/model-select";

export function App() {
  const [temperature, setTemperature] = useState(0.5)
  const [videoId, setVideoId] = useState<string | null>(null)

  const {
    input,
    setInput,
    handleInputChange,
    handleSubmit,
    completion,
    isLoading
  } = useCompletion({
    api: 'http://localhost:3333/ai/generate',
    body: {
      videoId,
      temperature,
    },
    headers: {
      'Content-Type': 'application/json',
    }
  })

  return (
    <div className="min-h-screen flex flex-col">
      <header className="px-6 py-3 flex items-center justify-between border-b">
        <h1 className="text-xl font-bold">upload.ai</h1>

        <div className="flex items-center gap-3">
          <span className="text-sm text-muted-foreground">Developed with 💙 by Lucas Ribeiro</span>

          <Separator orientation="vertical" className="h-6" />

          <Button variant='outline' asChild>
            <a target="_blank" href="https://github.com/luc-ribeiro">
              <GithubLogo size="1.5rem" className='mr-2' />
              Github
            </a>
          </Button>
        </div>
      </header>

      <main className="flex-1 p-6 flex gap-6">
        <div className="flex flex-col flex-1 gap-4">
          <div className="grid grid-rows-2 gap-4 flex-1">
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Add the prompt for the AI..."
              value={input}
              onChange={handleInputChange}
            />
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Result generated by the AI..." readOnly
              value={completion}
            />
          </div>

          <p className="text-ms text-muted-foreground">Remember: you can use the variable <code className="text-violet-400">{'{transcription}'}</code> in your prompt to add the transcription content in the selected video.</p>
        </div>
        <aside className="w-80 space-y-6">
          <VideoInputForm onVideoUploaded={setVideoId} />

          <Separator />

          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="space-y-2">
              <Label>Prompt</Label>
              <PromptSelect onPromptSelected={setInput} />
            </div>

            <div className="space-y-2">
              <ModelSelect />
            </div>

            <Separator />

            <div className="space-y-4">
              <Label>Temperature</Label>

              <Slider
                min={0}
                max={1}
                step={0.1}
                value={[temperature]}
                onValueChange={value => setTemperature(value[0])}
              />

              <span className="block text-xs text-muted-foreground italic leading-relaxed">Higher values ​​tend to leave the results creative and with possible errors</span>
            </div>

            <Separator />

            <Button disabled={isLoading} type="submit" className="w-full">
              Generate
              <MagicWand size="1.5rem" className="ml-2" />
            </Button>
          </form>
        </aside>
      </main>
    </div>
  )
}
